In [1]:
import pandas as pd
import numpy as np

In [11]:
df = pd.read_csv("./shared/data/products_extended.csv")
df.head()

,category,subcategory,name,description,url,price,image
0,jewelry,bracelet,Southwest Bracelet,The Southwest Bracelet combines elegance with ...,/images/Southwest_Bracelet.jpg,169.99,/images/Southwest_Bracelet.jpg
1,jewelry,bracelet,Jeweled Bracelet Watch,"Introducing the Jeweled Bracelet Watch, a styl...",/images/Jeweled_Bracelet_Watch.jpg,259.99,/images/Jeweled_Bracelet_Watch.jpg
2,jewelry,bracelet,Isis Bracelet,The Isis Bracelet add glamour to any outfit. T...,/images/Isis_Bracelet.jpg,269.99,/images/Isis_Bracelet.jpg
3,jewelry,bracelet,Butterfly Mixed Metal Bracelet,Introducing the Butterfly Mixed Metal Bracelet...,/images/Butterfly_Mixed_Metal_Bracelet.jpg,89.99,/images/Butterfly_Mixed_Metal_Bracelet.jpg
4,jewelry,bracelet,Butterfly Gold Chain Bracelet,"Introducing the Butterfly Gold Chain Bracelet,...",/images/Butterfly_Gold_Chain_Bracelet.jpg,59.99,/images/Butterfly_Gold_Chain_Bracelet.jpg

In [7]:
df = pd.read_csv("./shared/data/Product_Dataset_wImages.csv", encoding="latin1")
df['ProductName'] = df['ProductName'].str.replace("/", "_")
df['image'] = "/images/" + df['ProductName'].str.replace(" ", "_") + ".jpg"
clean_df = df.copy()
clean_df['name'] = clean_df['ProductName'].str.title()
clean_df['url'] = clean_df['image']
clean_df['image'] = clean_df['image']
clean_df['category'] = clean_df['LogisticsTaxonomyClassName']
clean_df['subcategory'] = clean_df['LogisticsTaxonomyGroupName']
clean_df['description'] = clean_df['MarketingText']
clean_df = clean_df[['category', 'subcategory', 'name', 'description','url', 'image']]
clean_df

,category,subcategory,name,description,url,image
0,Keyboards/Keypads,Keyboard Accessories,Ergotron Deep Kb Tray F_Workfit-Tx,Personalize your WorkFit-TX Standing Desk Conv...,/images/ERGOTRON_DEEP_KB_TRAY_F_WORKFIT-TX.jpg,/images/ERGOTRON_DEEP_KB_TRAY_F_WORKFIT-TX.jpg
1,Keyboards/Keypads,Keyboard Accessories,Ergotron Deep Kb Tray F_Workfit-Tx,Personalize your WorkFit-TX Standing Desk Conv...,/images/ERGOTRON_DEEP_KB_TRAY_F_WORKFIT-TX.jpg,/images/ERGOTRON_DEEP_KB_TRAY_F_WORKFIT-TX.jpg
2,Keyboards/Keypads,Keyboard Accessories,Ergotron Deep Kb Tray F_Workfit-Tx,Personalize your WorkFit-TX Standing Desk Conv...,/images/ERGOTRON_DEEP_KB_TRAY_F_WORKFIT-TX.jpg,/images/ERGOTRON_DEEP_KB_TRAY_F_WORKFIT-TX.jpg
3,Keyboards/Keypads,Keyboard Accessories,Ergotron Deep Kb Tray F_Workfit-Tx,Personalize your WorkFit-TX Standing Desk Conv...,/images/ERGOTRON_DEEP_KB_TRAY_F_WORKFIT-TX.jpg,/images/ERGOTRON_DEEP_KB_TRAY_F_WORKFIT-TX.jpg
4,Keyboards/Keypads,Keyboard Accessories,Ergotron Deep Kb Tray F_Workfit-Tx,Personalize your WorkFit-TX Standing Desk Conv...,/images/ERGOTRON_DEEP_KB_TRAY_F_WORKFIT-TX.jpg,/images/ERGOTRON_DEEP_KB_TRAY_F_WORKFIT-TX.jpg
...,...,...,...,...,...,...
5995,Small & Consumer Electronics,2-Way Radios/Walkie Talkies,Motorola On-Site 2 Way Radio,Empower your team with a faster way to communi...,/images/MOTOROLA_ON-SITE_2_WAY_RADIO.jpg,/images/MOTOROLA_ON-SITE_2_WAY_RADIO.jpg
5996,Small & Consumer Electronics,2-Way Radios/Walkie Talkies,Motorola On-Site 2 Way Radio,Empower your team with a faster way to communi...,/images/MOTOROLA_ON-SITE_2_WAY_RADIO.jpg,/images/MOTOROLA_ON-SITE_2_WAY_RADIO.jpg
5997,Small & Consumer Electronics,2-Way Radios/Walkie Talkies,Motorola On-Site 2 Way Radio,Empower your team with a faster way to communi...,/images/MOTOROLA_ON-SITE_2_WAY_RADIO.jpg,/images/MOTOROLA_ON-SITE_2_WAY_RADIO.jpg
5998,Small & Consumer Electronics,2-Way Radios/Walkie Talkies,Motorola On-Site 2 Way Radio,Empower your team with a faster way to communi...,/images/MOTOROLA_ON-SITE_2_WAY_RADIO.jpg,/images/MOTOROLA_ON-SITE_2_WAY_RADIO.jpg
5999,Small & Consumer Electronics,2-Way Radios/Walkie Talkies,Motorola On-Site 2 Way Radio,Empower your team with a faster way to communi...,/images/MOTOROLA_ON-SITE_2_WAY_RADIO.jpg,/images/MOTOROLA_ON-SITE_2_WAY_RADIO.jpg

In [ ]:
unique_df = clean_df.drop_duplicates()
unique_df['price'] = np.round(np.random.uniform(30, 100, size=len(unique_df)), 2)
unique_df = unique_df.reset_index(drop=True)
unique_df = unique_df[['category', 'subcategory', 'name', 'description','url','price', 'image']]
unique_df
unique_df.to_csv("./shared/data/cdw_products.csv", index=False)

/tmp/ipykernel_2137594/217917416.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  unique_df['price'] = np.round(np.random.uniform(30, 100, size=len(unique_df)), 2)

,category,subcategory,name,description,url,price,image
0,Keyboards/Keypads,Keyboard Accessories,Ergotron Deep Kb Tray F_Workfit-Tx,Personalize your WorkFit-TX Standing Desk Conv...,/images/ERGOTRON_DEEP_KB_TRAY_F_WORKFIT-TX.jpg,63.78,/images/ERGOTRON_DEEP_KB_TRAY_F_WORKFIT-TX.jpg
1,Keyboards/Keypads,Keyboard and Mouse Bundle,Kensington Kb For Life Wireless Cmbo,"Mouse Dimensions: 3.8"" x 2.3"" x 1.3"" (96.4mm x...",/images/KENSINGTON_KB_FOR_LIFE_WIRELESS_CMBO.jpg,99.53,/images/KENSINGTON_KB_FOR_LIFE_WIRELESS_CMBO.jpg
2,Keyboards/Keypads,Keyboards,Ikey Sealed Touchpad Keyboard,The EKSB-97-TP is one of the very thin product...,/images/IKEY_SEALED_TOUCHPAD_KEYBOARD.jpg,30.04,/images/IKEY_SEALED_TOUCHPAD_KEYBOARD.jpg
3,Keyboards/Keypads,Keyboards,Ken Pro Fit Wash Kb-Blk,You wash your hands to protect yourself from g...,/images/KEN_PRO_FIT_WASH_KB-BLK.jpg,71.72,/images/KEN_PRO_FIT_WASH_KB-BLK.jpg
4,Keyboards/Keypads,Keyboard Accessories,Chief Kb Tray Access Blk,The Chief keyboard tray monitor mount is perfe...,/images/CHIEF_KB_TRAY_ACCESS_BLK.jpg,81.27,/images/CHIEF_KB_TRAY_ACCESS_BLK.jpg
5,Keyboards/Keypads,Numeric Keypads,Pi Engineering Xk-60 Usb 60 Keys,60 re-legendable keys<br><br>Addressable blue ...,/images/PI_ENGINEERING_XK-60_USB_60_KEYS.jpg,43.91,/images/PI_ENGINEERING_XK-60_USB_60_KEYS.jpg
6,Keyboards/Keypads,Numeric Keypads,Genovation Lcd Mini Term 12 Usb,The Genovation MiniTerm 904 is a fully program...,/images/GENOVATION_LCD_MINI_TERM_12_USB.jpg,64.88,/images/GENOVATION_LCD_MINI_TERM_12_USB.jpg
7,Keyboards/Keypads,Keyboards,Ikey Slim Dual Connectivity Kb,This fully-sealed keyboard is designed to meet...,/images/IKEY_SLIM_DUAL_CONNECTIVITY_KB.jpg,34.84,/images/IKEY_SLIM_DUAL_CONNECTIVITY_KB.jpg
8,Keyboards/Keypads,Wireless Keyboards,Keyovation Goldtouch Go Kb & Nb Stnd,The Goldtouch Go!2 ErogSuite Bundle combines t...,/images/KEYOVATION_GOLDTOUCH_GO_KB_&_NB_STND.jpg,51.83,/images/KEYOVATION_GOLDTOUCH_GO_KB_&_NB_STND.jpg
9,Keyboards/Keypads,Keyboards,Esterline Med Essential 104 Usb Kb,"The flat, silicon surface of the Medigenic Ess...",/images/ESTERLINE_MED_ESSENTIAL_104_USB_KB.jpg,71.89,/images/ESTERLINE_MED_ESSENTIAL_104_USB_KB.jpg
10,Keyboards/Keypads,Keyboards,Pi Engineering Xkeys Xk-24 Usb Kb,The X-keys XK-24 features 24 keys with indepen...,/images/PI_ENGINEERING__XKEYS_XK-24_USB_KB.jpg,55.72,/images/PI_ENGINEERING__XKEYS_XK-24_USB_KB.jpg
11,Keyboards/Keypads,Keyboards,Kinesis Freestyle Pro Keyboard,The award-winning Freestyle Pro keyboard offer...,/images/KINESIS_FREESTYLE_PRO_KEYBOARD.jpg,62.74,/images/KINESIS_FREESTYLE_PRO_KEYBOARD.jpg
12,Keyboards/Keypads,Keyboards,Ikey Nema 4X Led Usb Kb W_Trackball,The DBL-810-TB is constructed using a highly r...,/images/IKEY_NEMA_4X_LED_USB_KB_W_TRACKBALL.jpg,66.82,/images/IKEY_NEMA_4X_LED_USB_KB_W_TRACKBALL.jpg
13,Keyboards/Keypads,Keyboards,Ikey Sealed Mobile Kb W_Touchpad,The SB-87-TP is iKey's thinnest keyboard to da...,/images/IKEY_SEALED_MOBILE_KB_W_TOUCHPAD.jpg,71.98,/images/IKEY_SEALED_MOBILE_KB_W_TOUCHPAD.jpg
14,Keyboards/Keypads,Keyboard Accessories,Ken Underdesk Kb Drawer,Keyboard drawer mounts under desk and easily g...,/images/KEN_UNDERDESK_KB_DRAWER.jpg,91.65,/images/KEN_UNDERDESK_KB_DRAWER.jpg
15,Keyboards/Keypads,Keyboards,"Cherry 11"" Ultraslim Kb-Gry",This compact keyboard is the perfect solution ...,"/images/CHERRY_11""_ULTRASLIM_KB-GRY.jpg",42.46,"/images/CHERRY_11""_ULTRASLIM_KB-GRY.jpg"
16,Keyboards/Keypads,Keyboards,Kensington Pro Fit Ergo Wrls Kb Blk,With its split and sloped keyboard with adjust...,/images/KENSINGTON_PRO_FIT_ERGO_WRLS_KB_BLK.jpg,72.58,/images/KENSINGTON_PRO_FIT_ERGO_WRLS_KB_BLK.jpg
17,Keyboards/Keypads,Keyboards,Ikey Sk-97-Tp Usb Kb W_Tp-Wht,iKeys new SK-97-TP keyboard provides users wi...,/images/IKEY_SK-97-TP_USB_KB_W_TP-WHT.jpg,77.02,/images/IKEY_SK-97-TP_USB_KB_W_TP-WHT.jpg
18,Keyboards/Keypads,Numeric Keypads,Lvo Usb Numeric Keypad Gen Ii,"No matter what type of professional you are, y...",/images/LVO_USB_NUMERIC_KEYPAD_GEN_II.jpg,41.02,/images/LVO_USB_NUMERIC_KEYPAD_GEN_II.jpg
19,Keyboards/Keypads,Keyboards,Ikey Du-5K Nema 4 Industrial Kb,The DU-5K-TP2 is a NEMA 4X rated keyboard with...,/images/IKEY_DU-5K_NEMA_4_INDUSTRIAL_KB.jpg,64.87,/images/IKEY_DU-5K_NEMA_4_INDUSTRIAL_KB.jpg
20,Keyboards/Keypads,Keyboards,Ikey Usb Keyboard Backlit Sealed,iKey's innovative SL-91 mobile keyboard was de...,/images/IKEY_USB_KEYBOARD_BACKLIT_SEALED.jpg,99.74,/images/IKEY_USB_KEYBOARD_BACKLIT_SEALED.jpg
21,Mice and Trackballs,Wired Mice,Kensington Pro Fit Ergo Wired Blk,With its built-in wrist support and neutral gr...,/images/KENSINGTON_PRO_FIT_ERGO_WIRED_BLK.jpg,78.96,/images/KENSINGTON_PRO_FIT_ERGO_WIRED_BLK.jpg
22,Mice and Trackballs,Wired Mice,Adesso Wrls Programmable Mouse,<p><b>2.4GHz Wireless Connectivity</b></p> <p>...,/images/ADESSO_WRLS_PROGRAMMABLE_MOUSE.jpg,58.27,/images/ADESSO_WRLS_PROGRAMMABLE_MOUSE.jpg
23,Mice and Trackballs,Wired Mice,Verb Usb Mini Travel Opt Mou Blk,Go Mini! This mini optical travel mouse works ...,/images/VERB_USB_MINI_TRAVEL_OPT_MOU_BLK.jpg,69.84,/images/VERB_USB_MINI_TRAVEL_OPT_MOU_BLK.jpg
24,Mice and Trackballs,Mouse/Wrist Pads,Fel Gel Wristrest_Mousepad Microban,The comfort of gel with added protection again...,/images/FEL_GEL_WRISTREST_MOUSEPAD_MICROBAN.jpg,35.55,/images/FEL_GEL_WRISTREST_MOUSEPAD_MICROBAN.jpg
25,Mice and Trackballs,Mouse/Wrist Pads,Fellowes Microban Thin Mouse Pad Gry,<p>Microban antimicrobial protection helps kee...,/images/FELLOWES_MICROBAN_THIN_MOUSE_PAD_GRY.jpg,38.14,/images/FELLOWES_MICROBAN_THIN_MOUSE_PAD_GRY.jpg
26,Mice and Trackballs,Wired Mice,Ikey Nema 4X Industrial Trackball,The DT-TB offers solid-state laser trackball t...,/images/IKEY_NEMA_4X_INDUSTRIAL_TRACKBALL.jpg,73.75,/images/IKEY_NEMA_4X_INDUSTRIAL_TRACKBALL.jpg
27,Mice and Trackballs,Wired Mice,Seal Shield Storm Medical Opt Mou,SILVER STORM Medical Grade Optical Mouse With ...,/images/SEAL_SHIELD_STORM_MEDICAL_OPT_MOU.jpg,30.86,/images/SEAL_SHIELD_STORM_MEDICAL_OPT_MOU.jpg
28,Mice and Trackballs,Wired Mice,Pioneer Ip68 Usb Mouse White,NaN,/images/PIONEER_IP68_USB_MOUSE_WHITE.jpg,87.02,/images/PIONEER_IP68_USB_MOUSE_WHITE.jpg
29,Mice and Trackballs,Wireless Mice,Verbatim Silent Wrls Mouse,Say goodbye to noise and hello to silence with...,/images/VERBATIM_SILENT_WRLS_MOUSE.jpg,88.72,/images/VERBATIM_SILENT_WRLS_MOUSE.jpg
30,Mice and Trackballs,Wireless Mice,Evoluent Wrls Vert Mouse 4 Rt Hand,Evoluent ®USB Wireless Right-Handed VerticalMo...,/images/EVOLUENT_WRLS_VERT_MOUSE_4_RT_HAND.jpg,74.40,/images/EVOLUENT_WRLS_VERT_MOUSE_4_RT_HAND.jpg
31,Mice and Trackballs,Wireless Mice,Verb Wrls Mini Travel Grap Mou,Go Mini! Verbatims new Nano travel mouse is u...,/images/VERB_WRLS_MINI_TRAVEL_GRAP_MOU.jpg,38.26,/images/VERB_WRLS_MINI_TRAVEL_GRAP_MOU.jpg
32,Mice and Trackballs,Wired Mice,Targus Opt Nb Usb Mou,The Targus USB Optical Laptop Mouse is a three...,/images/TARGUS_OPT_NB_USB_MOU.jpg,92.91,/images/TARGUS_OPT_NB_USB_MOU.jpg
33,Computer Displays,"Gaming Monitors 15""-34""",Benq Ex3410R Mobiuz 34In Gaming Mon,Go ahead and enter a gaming world where you wi...,/images/BENQ_EX3410R_MOBIUZ_34IN_GAMING_MON.jpg,92.09,/images/BENQ_EX3410R_MOBIUZ_34IN_GAMING_MON.jpg
34,Computer Displays,"24"" Computer Displays",Planar Pll2450Mw 24In Led Lcd Mon,"The Planar PLL2450MW 24"" Full HD LCD desktop m...",/images/PLANAR_PLL2450MW_24IN_LED_LCD_MON.jpg,59.93,/images/PLANAR_PLL2450MW_24IN_LED_LCD_MON.jpg
35,Notebook Computers,Clearance Merchandise,Acer C734T-C6As N4500 32_8 (Bstk),<p>The Acer Chromebook 511 C734T is a school l...,/images/ACER_C734T-C6AS_N4500_32_8_(BSTK).jpg,55.34,/images/ACER_C734T-C6AS_N4500_32_8_(BSTK).jpg
36,Apple Notebooks,MacBook Pro Notebooks,Apple Mbp 14 M3P 11C14C 18 512Gb Sb,"Apple Intelligence helps you write, express yo...",/images/APPLE_MBP_14_M3P_11C14C_18_512GB_SB.jpg,85.03,/images/APPLE_MBP_14_M3P_11C14C_18_512GB_SB.jpg
37,Apple Notebooks,Liquidation Items,Apple Mbp 14 M4P 12C16C 24G 512G Sil,The 14-inch MacBook Pro with M4 Pro and M4 Max...,/images/APPLE_MBP_14_M4P_12C16C_24G_512G_SIL.jpg,54.77,/images/APPLE_MBP_14_M4P_12C16C_24G_512G_SIL.jpg
38,Apple Notebooks,Liquidation Items,Apple Mbp 16Nt M4M 16C40C 64 1Tb Sb,The 16-inch MacBook Pro with M4 Pro and M4 Max...,/images/APPLE_MBP_16NT_M4M_16C40C_64_1TB_SB.jpg,83.61,/images/APPLE_MBP_16NT_M4M_16C40C_64_1TB_SB.jpg
39,Apple Notebooks,MacBook Notebooks,Apple Mba 13 M2 8C8C 16 8Gb 256 Str,Apple Intelligence is the personal intelligenc...,/images/APPLE_MBA_13_M2_8C8C_16_8GB_256__STR.jpg,65.93,/images/APPLE_MBA_13_M2_8C8C_16_8GB_256__STR.jpg
40,Apple Notebooks,MacBook Pro Notebooks,Apple Mbp 14Nt M4M 16C40C 128 8T Sil,The display on the 14-inch MacBook Pro has rou...,/images/APPLE_MBP_14NT_M4M_16C40C_128_8T_SIL.jpg,66.99,/images/APPLE_MBP_14NT_M4M_16C40C_128_8T_SIL.jpg
41,Apple Notebooks,MacBook Notebooks,Apple Mba 13 M2 8C10C 16 1Tb Mn 70W,"Supercharged by the M2 chip, the redesigned 13...",/images/APPLE_MBA_13_M2_8C10C_16_1TB_MN_70W.jpg,70.18,/images/APPLE_MBA_13_M2_8C10C_16_1TB_MN_70W.jpg
42,Small & Consumer Electronics,Desktop Webcams,Aluratek Webcam 1080P Hd,Aluratek's HD 1080p webcam with autofocus lets...,/images/ALURATEK_WEBCAM_1080P_HD.jpg,53.27,/images/ALURATEK_WEBCAM_1080P_HD.jpg
43,Small & Consumer Electronics,Calculators,Texas Ti Nspire Cx Ii Graphing Calcu,<p>The Texas Instruments TI-Nspire CX II Graph...,/images/TEXAS_TI_NSPIRE_CX_II_GRAPHING_CALCU.jpg,58.05,/images/TEXAS_TI_NSPIRE_CX_II_GRAPHING_CALCU.jpg
44,Small & Consumer Electronics,2-Way Radios/Walkie Talkies,Motorola On-Site 2 Way Radio,Empower your team with a faster way to communi...,/images/MOTOROLA_ON-SITE_2_WAY_RADIO.jpg,97.00,/images/MOTOROLA_ON-SITE_2_WAY_RADIO.jpg
45,Small & Consumer Electronics,Tools,C2G Rj45 Plug Cover - 6.0Mm Gry 50Pk,Complete the look of your patch cables with th...,/images/C2G_RJ45_PLUG_COVER_-_6.0MM_GRY_50PK.jpg,59.61,/images/C2G_RJ45_PLUG_COVER_-_6.0MM_GRY_50PK.jpg
46,Small & Consumer Electronics,Gaming Controllers,Logitech Driving Force Shifter 29,<p>The sim racing shifter for G29 and G920 Dri...,/images/LOGITECH_DRIVING_FORCE_SHIFTER_29.jpg,69.89,/images/LOGITECH_DRIVING_FORCE_SHIFTER_29.jpg
47,Small & Consumer Electronics,Tools,C2G 1Rnd_Flat Cut Strip Tool,"<p>With its adjustable stripping depth, this t...",/images/C2G_1RND_FLAT_CUT_STRIP_TOOL.jpg,32.94,/images/C2G_1RND_FLAT_CUT_STRIP_TOOL.jpg
48,Small & Consumer Electronics,Gaming Controllers,Logitech Gamepad F310,<p><b>Extensive game support</b></p> <p>Play h...,/images/LOGITECH_GAMEPAD_F310.jpg,81.00,/images/LOGITECH_GAMEPAD_F310.jpg

In [14]:
unique_df['subcategory'].unique()

array(['Numeric Keypads', 'Keyboards', 'Keyboard Accessories',
       'Keyboard and Mouse Bundle', 'Wireless Keyboards', 'Wired Mice',
       'Mouse/Wrist Pads', 'Wireless Mice', 'Gaming Monitors 15"-34"',
       '24" Computer Displays', 'Clearance Merchandise', 'Chromebooks',
       'Liquidation Items', 'MacBook Pro Notebooks', 'MacBook Notebooks',
       'Desktop Webcams', 'Calculators', 'Gaming Controllers', 'Tools',
       'Voice/Portable Recorders', 'Digitizer Tablets/Stylus'],
      dtype=object)

In [24]:
df2 = pd.read_csv("./shared/data/cdw_products.csv")
df2['url'] = "http://localhost:3000/images/" + df2['url'].str[12:]
df2['image'] = df2['url']
df2.to_csv("./shared/data/clean_cdw_products.csv", index=False)