In [10]:
import pandas as pd
import numpy as np

In [11]:
df = pd.read_csv("./shared/data/products_extended.csv")
df.head()

,category,subcategory,name,description,url,price,image
0,jewelry,bracelet,Southwest Bracelet,The Southwest Bracelet combines elegance with ...,/images/Southwest_Bracelet.jpg,169.99,/images/Southwest_Bracelet.jpg
1,jewelry,bracelet,Jeweled Bracelet Watch,"Introducing the Jeweled Bracelet Watch, a styl...",/images/Jeweled_Bracelet_Watch.jpg,259.99,/images/Jeweled_Bracelet_Watch.jpg
2,jewelry,bracelet,Isis Bracelet,The Isis Bracelet add glamour to any outfit. T...,/images/Isis_Bracelet.jpg,269.99,/images/Isis_Bracelet.jpg
3,jewelry,bracelet,Butterfly Mixed Metal Bracelet,Introducing the Butterfly Mixed Metal Bracelet...,/images/Butterfly_Mixed_Metal_Bracelet.jpg,89.99,/images/Butterfly_Mixed_Metal_Bracelet.jpg
4,jewelry,bracelet,Butterfly Gold Chain Bracelet,"Introducing the Butterfly Gold Chain Bracelet,...",/images/Butterfly_Gold_Chain_Bracelet.jpg,59.99,/images/Butterfly_Gold_Chain_Bracelet.jpg

In [12]:
df = pd.read_csv("./shared/data/Product_Dataset_wImages.csv", encoding="latin1")
df['image'] = "/cdw_images/" + df['ProductName'].str.replace(" ", "_") + ".jpg"
clean_df = df.copy()
clean_df['name'] = clean_df['ProductName'].str.title()
clean_df['url'] = clean_df['image']
clean_df['image'] = clean_df['image']
clean_df['category'] = clean_df['LogisticsTaxonomyClassName']
clean_df['subcategory'] = clean_df['LogisticsTaxonomyGroupName']
clean_df['description'] = clean_df['MarketingText']
clean_df = clean_df[['category', 'subcategory', 'name', 'description','url', 'image']]
clean_df

,category,subcategory,name,description,url,image
0,Keyboards/Keypads,Numeric Keypads,Genovation Lcd Mini Term 12 Usb,The Genovation MiniTerm 904 is a fully program...,/cdw_images/GENOVATION_LCD_MINI_TERM_12_USB.jpg,/cdw_images/GENOVATION_LCD_MINI_TERM_12_USB.jpg
1,Keyboards/Keypads,Numeric Keypads,Genovation Lcd Mini Term 12 Usb,The Genovation MiniTerm 904 is a fully program...,/cdw_images/GENOVATION_LCD_MINI_TERM_12_USB.jpg,/cdw_images/GENOVATION_LCD_MINI_TERM_12_USB.jpg
2,Keyboards/Keypads,Numeric Keypads,Genovation Lcd Mini Term 12 Usb,The Genovation MiniTerm 904 is a fully program...,/cdw_images/GENOVATION_LCD_MINI_TERM_12_USB.jpg,/cdw_images/GENOVATION_LCD_MINI_TERM_12_USB.jpg
3,Keyboards/Keypads,Numeric Keypads,Genovation Lcd Mini Term 12 Usb,The Genovation MiniTerm 904 is a fully program...,/cdw_images/GENOVATION_LCD_MINI_TERM_12_USB.jpg,/cdw_images/GENOVATION_LCD_MINI_TERM_12_USB.jpg
4,Keyboards/Keypads,Numeric Keypads,Genovation Lcd Mini Term 12 Usb,The Genovation MiniTerm 904 is a fully program...,/cdw_images/GENOVATION_LCD_MINI_TERM_12_USB.jpg,/cdw_images/GENOVATION_LCD_MINI_TERM_12_USB.jpg
...,...,...,...,...,...,...
5995,Small & Consumer Electronics,Tools,Fluke Eversharp 66/110 Blade Punch,Fluke Networks increases the versatility and f...,/cdw_images/FLUKE_EVERSHARP_66/110_BLADE_PUNCH...,/cdw_images/FLUKE_EVERSHARP_66/110_BLADE_PUNCH...
5996,Small & Consumer Electronics,Tools,Fluke Eversharp 66/110 Blade Punch,Fluke Networks increases the versatility and f...,/cdw_images/FLUKE_EVERSHARP_66/110_BLADE_PUNCH...,/cdw_images/FLUKE_EVERSHARP_66/110_BLADE_PUNCH...
5997,Small & Consumer Electronics,Tools,Fluke Eversharp 66/110 Blade Punch,Fluke Networks increases the versatility and f...,/cdw_images/FLUKE_EVERSHARP_66/110_BLADE_PUNCH...,/cdw_images/FLUKE_EVERSHARP_66/110_BLADE_PUNCH...
5998,Small & Consumer Electronics,Tools,Fluke Eversharp 66/110 Blade Punch,Fluke Networks increases the versatility and f...,/cdw_images/FLUKE_EVERSHARP_66/110_BLADE_PUNCH...,/cdw_images/FLUKE_EVERSHARP_66/110_BLADE_PUNCH...
5999,Small & Consumer Electronics,Tools,Fluke Eversharp 66/110 Blade Punch,Fluke Networks increases the versatility and f...,/cdw_images/FLUKE_EVERSHARP_66/110_BLADE_PUNCH...,/cdw_images/FLUKE_EVERSHARP_66/110_BLADE_PUNCH...

In [13]:
unique_df = clean_df.drop_duplicates()
unique_df['price'] = np.round(np.random.uniform(30, 100, size=len(unique_df)), 2)
unique_df = unique_df.reset_index(drop=True)
unique_df = unique_df[['category', 'subcategory', 'name', 'description','url','price', 'image']]
# unique_df.to_csv("./shared/data/clean_cdw_products.csv", index=False)

/tmp/ipykernel_3921977/4262974395.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  unique_df['price'] = np.round(np.random.uniform(30, 100, size=len(unique_df)), 2)

In [14]:
unique_df['subcategory'].unique()

array(['Numeric Keypads', 'Keyboards', 'Keyboard Accessories',
       'Keyboard and Mouse Bundle', 'Wireless Keyboards', 'Wired Mice',
       'Mouse/Wrist Pads', 'Wireless Mice', 'Gaming Monitors 15"-34"',
       '24" Computer Displays', 'Clearance Merchandise', 'Chromebooks',
       'Liquidation Items', 'MacBook Pro Notebooks', 'MacBook Notebooks',
       'Desktop Webcams', 'Calculators', 'Gaming Controllers', 'Tools',
       'Voice/Portable Recorders', 'Digitizer Tablets/Stylus'],
      dtype=object)

In [24]:
df2 = pd.read_csv("./shared/data/cdw_products.csv")
df2['url'] = "http://localhost:3000/images/" + df2['url'].str[12:]
df2['image'] = df2['url']
df2.to_csv("./shared/data/clean_cdw_products.csv", index=False)