In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("./shared/data/products.csv")
df.head()

,category,subcategory,name,description,url,price,image
0,accessories,bag,Classic Black Patent Leather Purse,"Introducing the Classic Black Patent Bag, a bl...",/images/Classic_Black_Patent_Leather_Purse1-sm...,49.9,/images/Classic_Black_Patent_Leather_Purse1-sm...
1,accessories,bag,Embroidered Cream Purse with Gold Detail,Introducing the Embroidered Cream purse with g...,/images/Creme_clutch_purse1-small.jpg,69.9,/images/Creme_clutch_purse1-small.jpg
2,accessories,bag,Ratan Basket Shoulder Bag,The Ratan Basket Shoulder Bag is a charming bl...,/images/Ratan_Basket_Shoulder_Bag-small2.jpg,89.9,/images/Ratan_Basket_Shoulder_Bag-small2.jpg
3,accessories,bag,Embroidered Leather Bohemian Purse,"Introducing the Embroidered Fabric Purse, a de...",/images/Embroidered_Leather_Bohemian_Purse-sma...,49.9,/images/Embroidered_Leather_Bohemian_Purse-sma...
4,apparel,dress,Black Polka-Dotted Slip Dress,Discover timeless elegance with our Black Polk...,/images/Black_Polka_Dotted_Slip_Dress.jpeg,59.9,/images/Black_Polka_Dotted_Slip_Dress.jpeg

In [3]:
df = pd.read_csv("./shared/data/Product_Dataset_wImages.csv", encoding="latin1")
df['image'] = "/cdw_images/" + df['ProductName'].str.replace(" ", "_") + ".jpg"
clean_df = df.copy()
clean_df['name'] = clean_df['ProductName'].str.title()
clean_df['url'] = clean_df['image']
clean_df['image'] = clean_df['image']
clean_df['category'] = clean_df['LogisticsTaxonomyClassName']
clean_df['subcategory'] = clean_df['LogisticsTaxonomyGroupName']
clean_df['description'] = clean_df['MarketingText']
clean_df = clean_df[['category', 'subcategory', 'name', 'description','url', 'image']]
clean_df

,category,subcategory,name,description,url,image
0,Keyboards/Keypads,Numeric Keypads,Genovation Lcd Mini Term 12 Usb,The Genovation MiniTerm 904 is a fully program...,/cdw_images/GENOVATION_LCD_MINI_TERM_12_USB.jpg,/cdw_images/GENOVATION_LCD_MINI_TERM_12_USB.jpg
1,Keyboards/Keypads,Numeric Keypads,Genovation Lcd Mini Term 12 Usb,The Genovation MiniTerm 904 is a fully program...,/cdw_images/GENOVATION_LCD_MINI_TERM_12_USB.jpg,/cdw_images/GENOVATION_LCD_MINI_TERM_12_USB.jpg
2,Keyboards/Keypads,Numeric Keypads,Genovation Lcd Mini Term 12 Usb,The Genovation MiniTerm 904 is a fully program...,/cdw_images/GENOVATION_LCD_MINI_TERM_12_USB.jpg,/cdw_images/GENOVATION_LCD_MINI_TERM_12_USB.jpg
3,Keyboards/Keypads,Numeric Keypads,Genovation Lcd Mini Term 12 Usb,The Genovation MiniTerm 904 is a fully program...,/cdw_images/GENOVATION_LCD_MINI_TERM_12_USB.jpg,/cdw_images/GENOVATION_LCD_MINI_TERM_12_USB.jpg
4,Keyboards/Keypads,Numeric Keypads,Genovation Lcd Mini Term 12 Usb,The Genovation MiniTerm 904 is a fully program...,/cdw_images/GENOVATION_LCD_MINI_TERM_12_USB.jpg,/cdw_images/GENOVATION_LCD_MINI_TERM_12_USB.jpg
...,...,...,...,...,...,...
5995,Small & Consumer Electronics,Tools,Fluke Eversharp 66/110 Blade Punch,Fluke Networks increases the versatility and f...,/cdw_images/FLUKE_EVERSHARP_66/110_BLADE_PUNCH...,/cdw_images/FLUKE_EVERSHARP_66/110_BLADE_PUNCH...
5996,Small & Consumer Electronics,Tools,Fluke Eversharp 66/110 Blade Punch,Fluke Networks increases the versatility and f...,/cdw_images/FLUKE_EVERSHARP_66/110_BLADE_PUNCH...,/cdw_images/FLUKE_EVERSHARP_66/110_BLADE_PUNCH...
5997,Small & Consumer Electronics,Tools,Fluke Eversharp 66/110 Blade Punch,Fluke Networks increases the versatility and f...,/cdw_images/FLUKE_EVERSHARP_66/110_BLADE_PUNCH...,/cdw_images/FLUKE_EVERSHARP_66/110_BLADE_PUNCH...
5998,Small & Consumer Electronics,Tools,Fluke Eversharp 66/110 Blade Punch,Fluke Networks increases the versatility and f...,/cdw_images/FLUKE_EVERSHARP_66/110_BLADE_PUNCH...,/cdw_images/FLUKE_EVERSHARP_66/110_BLADE_PUNCH...
5999,Small & Consumer Electronics,Tools,Fluke Eversharp 66/110 Blade Punch,Fluke Networks increases the versatility and f...,/cdw_images/FLUKE_EVERSHARP_66/110_BLADE_PUNCH...,/cdw_images/FLUKE_EVERSHARP_66/110_BLADE_PUNCH...

In [ ]:
unique_df = clean_df.drop_duplicates()
unique_df['price'] = np.round(np.random.uniform(30, 100, size=len(unique_df)), 2)
unique_df = unique_df.reset_index(drop=True)
unique_df = unique_df[['category', 'subcategory', 'name', 'description','url','price', 'image']]
unique_df.to_csv("./shared/data/clean_cdw_products.csv", index=False)

/tmp/ipykernel_558059/2675632932.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  unique_df['price'] = np.round(np.random.uniform(30, 100, size=len(unique_df)), 2)

OSError: Cannot save file into a non-existent directory: '/shared/data'